# Generated by Django 6.0.7 on 2026-07-29 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolioApp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="view_project_link",
            field=models.CharField(default="#projects", max_length=100),
        ),
    ]
