# Generated by Django 6.0.7 on 2026-08-05 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolioApp", "0002_profile_view_project_link"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="technology",
        ),
        migrations.AddField(
            model_name="project",
            name="demo",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="technologies",
            field=models.CharField(
                default=("HTML", "CSS"),
                help_text="Example: HTML, CSS, Django, Python",
                max_length=250,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="project",
            name="github",
            field=models.URLField(blank=True, null=True),
        ),
    ]
