# Generated by Django 6.0.7 on 2026-08-05 15:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolioApp", "0003_remove_project_technology_project_demo_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="demo",
        ),
        migrations.RemoveField(
            model_name="project",
            name="technologies",
        ),
        migrations.AddField(
            model_name="project",
            name="technology",
            field=models.CharField(default=("HTML", "CSS", "Django"), max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="project",
            name="github",
            field=models.URLField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
