# Generated by Django 6.0.7 on 2026-08-05 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "portfolioApp",
            "0004_remove_project_demo_remove_project_technologies_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="education",
            name="Pointer",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="education",
            name="percentage",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
